spring.application.name=minimarket
# Configuraci�n de H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Configuraci�n de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

jwt.secret=8f3a9c7d2e1b4f6a9d8c5e2f7a1b3c6d9e4f8a2c7b5d1e6f9a3c8b2d7e4f1a6
jwt.expiration=360000